### ISSUE TITLE
git clone后报错

### ISSUE THREAD

**Issue by RyanJiang184** [RSRH-Rs/image_lssv#2]
git clone的连接好像给错了，而且使用方法感觉不太对劲
另外有如下报错：
File "C:\Users\Administrator\Desktop\Hoshino\HoshinoBot\hoshino\modules\Hoshino-plugin-image-lssv\__init__.py", line 11, in <module>
    from .config_image import get_image_services,convert_img
ImportError: cannot import name 'convert_img' from 'hoshino.modules.Hoshino-plugin-image-lssv.config_image' (C:\Users\Administrator\Desktop\Hoshino\HoshinoBot\hoshino\modules\Hoshino-plugin-image-lssv\config_image.py)
[2023-04-28 12:46:22,942 nonebot] ERROR: Failed to import and load "hoshino.modules.Hoshino-plugin-image-lssv.config_image", error: cannot import name 'convert_img' from 'hoshino.modules.Hoshino-plugin-image-lssv.config_image' (C:\Users\Administrator\Desktop\Hoshino\HoshinoBot\hoshino\modules\Hoshino-plugin-image-lssv\config_image.py)
[2023-04-28 12:46:22,957 nonebot] ERROR: cannot import name 'convert_img' from 'hoshino.modules.Hoshino-plugin-image-lssv.config_image' (C:\Users\Administrator\Desktop\Hoshino\HoshinoBot\hoshino\modules\Hoshino-plugin-image-lssv\config_image.py)
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Roaming\Python\Python38\site-packages\nonebot\plugin.py", line 419, in _load_plugin
    module = importlib.import_module(module_path)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Administrator\Desktop\Hoshino\HoshinoBot\hoshino\modules\Hoshino-plugin-image-lssv\__init__.py", line 11, in <module>
    from .config_image import get_image_services,convert_img
ImportError: cannot import name 'convert_img' from 'hoshino.modules.Hoshino-plugin-image-lssv.config_image' (C:\Users\Administrator\Desktop\Hoshino\HoshinoBot\hoshino\modules\Hoshino-plugin-image-lssv\config_image.py)
佬能帮忙看看吗？

**Comment by RSRH-Rs** [comment]
你重新clone一下然后在hoshino/config/__bot__.py中的MODULES_ON里，加入image_lssv然后把 hoshino/modules/botmanage/service_manage.py 这个文件删掉，运行看看
